language: python

sudo: true

python:
  - "3.6"
  - "3.9"

env:
  - TEST_TYPE=test

cache:
  directories:
  - $HOME/.cache/pip

install:
  - pip install pyarrow<6.0.0
  - pip install pandas<2.0.0
  - pip install numpy>=1.14.0
  - pip install ciso8601
  - make setup

script:
  - make ${TEST_TYPE}
